### GET request to example server
POST http://localhost:8080/api/admin/movies
###
Content-Type: form-data

key: movieRequest
value: {"title":"Harry Potter","genre":"Fantasy","date":"01-01-2005","rating": "PG13"}
file: moviePoster; @/path/to/your/image.jpg