### GET request to example server
#GET http://localhost:8080/api/movies/genre?genre=FANTASY
#GET http://localhost:8080/api/movies/genre?genre=FANTASY?topRated=true
GET http://localhost:8080/api/movies/genre?genre=FANTASY&sortBy=asc